//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integra.Service.Test.svcSoluglob_Integra {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="svcSoluglob_Integra.ISoluglob_Integra")]
    public interface ISoluglob_Integra {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoluglob_Integra/AltaEmpleadoSG", ReplyAction="http://tempuri.org/ISoluglob_Integra/AltaEmpleadoSGResponse")]
        int AltaEmpleadoSG(int IdEntrevistaCandidato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoluglob_Integra/AltaEmpleadoSG", ReplyAction="http://tempuri.org/ISoluglob_Integra/AltaEmpleadoSGResponse")]
        System.Threading.Tasks.Task<int> AltaEmpleadoSGAsync(int IdEntrevistaCandidato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoluglob_Integra/GetIncidenciasSG", ReplyAction="http://tempuri.org/ISoluglob_Integra/GetIncidenciasSGResponse")]
        System.Data.DataSet GetIncidenciasSG(System.DateTime FechaInicio, System.DateTime FechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoluglob_Integra/GetIncidenciasSG", ReplyAction="http://tempuri.org/ISoluglob_Integra/GetIncidenciasSGResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetIncidenciasSGAsync(System.DateTime FechaInicio, System.DateTime FechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoluglob_Integra/MovimientoEmpleadoSG", ReplyAction="http://tempuri.org/ISoluglob_Integra/MovimientoEmpleadoSGResponse")]
        bool MovimientoEmpleadoSG(string NumEmpleado, int IdRequisicionMovimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISoluglob_Integra/MovimientoEmpleadoSG", ReplyAction="http://tempuri.org/ISoluglob_Integra/MovimientoEmpleadoSGResponse")]
        System.Threading.Tasks.Task<bool> MovimientoEmpleadoSGAsync(string NumEmpleado, int IdRequisicionMovimiento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISoluglob_IntegraChannel : Integra.Service.Test.svcSoluglob_Integra.ISoluglob_Integra, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Soluglob_IntegraClient : System.ServiceModel.ClientBase<Integra.Service.Test.svcSoluglob_Integra.ISoluglob_Integra>, Integra.Service.Test.svcSoluglob_Integra.ISoluglob_Integra {
        
        public Soluglob_IntegraClient() {
        }
        
        public Soluglob_IntegraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Soluglob_IntegraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Soluglob_IntegraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Soluglob_IntegraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AltaEmpleadoSG(int IdEntrevistaCandidato) {
            return base.Channel.AltaEmpleadoSG(IdEntrevistaCandidato);
        }
        
        public System.Threading.Tasks.Task<int> AltaEmpleadoSGAsync(int IdEntrevistaCandidato) {
            return base.Channel.AltaEmpleadoSGAsync(IdEntrevistaCandidato);
        }
        
        public System.Data.DataSet GetIncidenciasSG(System.DateTime FechaInicio, System.DateTime FechaFin) {
            return base.Channel.GetIncidenciasSG(FechaInicio, FechaFin);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetIncidenciasSGAsync(System.DateTime FechaInicio, System.DateTime FechaFin) {
            return base.Channel.GetIncidenciasSGAsync(FechaInicio, FechaFin);
        }
        
        public bool MovimientoEmpleadoSG(string NumEmpleado, int IdRequisicionMovimiento) {
            return base.Channel.MovimientoEmpleadoSG(NumEmpleado, IdRequisicionMovimiento);
        }
        
        public System.Threading.Tasks.Task<bool> MovimientoEmpleadoSGAsync(string NumEmpleado, int IdRequisicionMovimiento) {
            return base.Channel.MovimientoEmpleadoSGAsync(NumEmpleado, IdRequisicionMovimiento);
        }
    }
}
