//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integra.Services.Test.Integra_Soluglob.svcIntegra_Soluglob {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="svcIntegra_Soluglob.IIntegra_Soluglob")]
    public interface IIntegra_Soluglob {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegra_Soluglob/AltaEmpleado", ReplyAction="http://tempuri.org/IIntegra_Soluglob/AltaEmpleadoResponse")]
        bool AltaEmpleado(int idEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegra_Soluglob/AltaEmpleado", ReplyAction="http://tempuri.org/IIntegra_Soluglob/AltaEmpleadoResponse")]
        System.Threading.Tasks.Task<bool> AltaEmpleadoAsync(int idEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegra_Soluglob/BajaEmpleado", ReplyAction="http://tempuri.org/IIntegra_Soluglob/BajaEmpleadoResponse")]
        bool BajaEmpleado(string compania, string numEmpleado, string motivo, int requisicionMovimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegra_Soluglob/BajaEmpleado", ReplyAction="http://tempuri.org/IIntegra_Soluglob/BajaEmpleadoResponse")]
        System.Threading.Tasks.Task<bool> BajaEmpleadoAsync(string compania, string numEmpleado, string motivo, int requisicionMovimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegra_Soluglob/MovimientoEmpleadoKaizen", ReplyAction="http://tempuri.org/IIntegra_Soluglob/MovimientoEmpleadoKaizenResponse")]
        bool MovimientoEmpleadoKaizen(string NumEmpleado, int IdRequisicionMovimiento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntegra_Soluglob/MovimientoEmpleadoKaizen", ReplyAction="http://tempuri.org/IIntegra_Soluglob/MovimientoEmpleadoKaizenResponse")]
        System.Threading.Tasks.Task<bool> MovimientoEmpleadoKaizenAsync(string NumEmpleado, int IdRequisicionMovimiento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntegra_SoluglobChannel : Integra.Services.Test.Integra_Soluglob.svcIntegra_Soluglob.IIntegra_Soluglob, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Integra_SoluglobClient : System.ServiceModel.ClientBase<Integra.Services.Test.Integra_Soluglob.svcIntegra_Soluglob.IIntegra_Soluglob>, Integra.Services.Test.Integra_Soluglob.svcIntegra_Soluglob.IIntegra_Soluglob {
        
        public Integra_SoluglobClient() {
        }
        
        public Integra_SoluglobClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Integra_SoluglobClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Integra_SoluglobClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Integra_SoluglobClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AltaEmpleado(int idEmpleado) {
            return base.Channel.AltaEmpleado(idEmpleado);
        }
        
        public System.Threading.Tasks.Task<bool> AltaEmpleadoAsync(int idEmpleado) {
            return base.Channel.AltaEmpleadoAsync(idEmpleado);
        }
        
        public bool BajaEmpleado(string compania, string numEmpleado, string motivo, int requisicionMovimiento) {
            return base.Channel.BajaEmpleado(compania, numEmpleado, motivo, requisicionMovimiento);
        }
        
        public System.Threading.Tasks.Task<bool> BajaEmpleadoAsync(string compania, string numEmpleado, string motivo, int requisicionMovimiento) {
            return base.Channel.BajaEmpleadoAsync(compania, numEmpleado, motivo, requisicionMovimiento);
        }
        
        public bool MovimientoEmpleadoKaizen(string NumEmpleado, int IdRequisicionMovimiento) {
            return base.Channel.MovimientoEmpleadoKaizen(NumEmpleado, IdRequisicionMovimiento);
        }
        
        public System.Threading.Tasks.Task<bool> MovimientoEmpleadoKaizenAsync(string NumEmpleado, int IdRequisicionMovimiento) {
            return base.Channel.MovimientoEmpleadoKaizenAsync(NumEmpleado, IdRequisicionMovimiento);
        }
    }
}
